export const navigationMenu = [
  { name: "Home", url: "/" },
  { name: "Products", url: "/products" },
  { name: "Shops", url: "/shops" },
  { name: "Today's Deals", url: "/todays_deals" },
  { name: "Best Sellers", url: "/best_sellers" },
  { name: "Become a Seller", url: "/become_a_seller" },
  { name: "Offers", url: "/hot_offers" },
  { name: "Blog", url: "/blog" },
  { name: "Contact Us", url: "/contact_us" },
];

export const categories = [
  {
    name: "Clothing",
    items: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Clothing",
      "Active wear",
      "Formal Wear",
      "Casual Wear",
    ],

    image: "images/category/clothing-1.jpg",
    url: "/clothing",
  },
  {
    name: "Footwear",
    items: [
      "Men's Shoes",
      "Women's Shoes",
      "Kids' Shoes",
      "Sneakers",
      "Sandals",
      "Boots",
    ],
    image: "images/category/shoes-2.jpg",
    url: "/footwear",
  },
  {
    name: "Electronics",
    items: [
      "Smartphones",
      "Laptops",
      "Tablets",
      "Cameras",
      "Headphones",
      "Smartwatches",
    ],
    image: "images/category/camera.jpg",
    url: "/electronics",
  },
  {
    name: "Home & Kitchen",
    items: [
      "Furniture",
      "Kitchen Appliances",
      "Home Decor",
      "Cookware",
      "Bedding",
      "Lighting",
    ],
    image: "images/category/kitchen.jpg",
    url: "/home_kitchen",
  },
  {
    name: "Automotive",
    items: [
      "Car Accessories",
      "Car Care",
      "Car Electronics",
      "Tires & Wheels",
      "Tools & Equipment",
      "Motorcycle Accessories",
    ],
    image: "images/category/automotive.jpg",
    url: "/automotive",
  },

  {
    name: "Sports & Outdoors",
    items: [
      "Fitness Equipment",
      "Outdoor Gear",
      "Team Sports",
      "Cycling",
      "Camping",
      "Yoga",
    ],
    image: "images/category/sport.jpg",
    url: "/sports_outdoors",
  },
  {
    name: "Toys & Games",
    items: [
      "Action Figures",
      "Board Games",
      "Puzzles",
      "Dolls",
      "Educational Toys",
      "Outdoor Toys",
    ],
    image: "images/category/toys.jpg",
    url: "/toys_games",
  },
  {
    name: "Books & Stationery",
    items: [
      "Fiction",
      "Non-Fiction",
      "Children's Books",
      "Notebooks",
      "Pens & Pencils",
      "Art Supplies",
    ],
    image: "images/category/books.jpg",
    url: "/books_stationery",
  },
  {
    name: "Jewelry & Accessories",
    items: [
      "Necklaces",
      "Earrings",
      "Bracelets",
      "Watches",
      "Sunglasses",
      "Handbags",
    ],
    image: "images/category/jewelry.jpg",
    url: "/jewelry_accessories",
  },
  {
    name: "Health & Wellness",
    items: [
      "Vitamins & Supplements",
      "Fitness Trackers",
      "Medical Supplies",
      "Personal Care",
      "Diet & Nutrition",
      "Mental Health",
    ],
    image: "images/category/health.jpg",
    url: "/health_wellness",
  },
  {
    name: "Baby & Maternity",
    items: [
      "Baby Clothing",
      "Baby Gear",
      "Maternity Wear",
      "Nursery Furniture",
      "Feeding Supplies",
      "Baby Toys",
    ],
    image: "images/category/maternity.jpg",
    url: "/baby_maternity",
  },
  {
    name: "Bags & Luggage",
    items: [
      "Backpacks",
      "Handbags",
      "Travel Bags",
      "Laptop Bags",
      "Wallets",
      "Suitcases",
    ],
    image: "images/category/bags.jpg",
    url: "/bags_luggage",
  },
  {
    name: "Office & School Supplies",
    items: [
      "Notebooks",
      "Pens & Pencils",
      "Desk Organizers",
      "Printers",
      "Stationery Sets",
      "Art Supplies",
    ],
    image: "images/category/office.jpg",
    url: "/office_school",
  },
  {
    name: "Pet Supplies",
    items: [
      "Pet Food",
      "Pet Toys",
      "Pet Beds",
      "Pet Grooming",
      "Pet Carriers",
      "Pet Accessories",
    ],
    image: "images/category/pet.jpg",
    url: "/pet_supplies",
  },
  // {
  //   name: "Appliances",
  //   items: [
  //     "Kitchen Appliances",
  //     "Home Appliances",
  //     "Cleaning Appliances",
  //     "Personal Care Appliances",
  //     "Smart Home Devices",
  //     "Air Conditioners",
  //   ],
  //   image: "images/category/appliances.jpg",
  //   url: "/appliances",
  // },
  {
    name: "Beauty & Personal Care",
    items: [
      "Skincare",
      "Makeup",
      "Haircare",
      "Fragrances",
      "Men's Grooming",
      "Wellness",
    ],
    image: "images/category/personalCare.jpg",
    url: "/beauty_personalCare",
  },
];

export const bestsellers = [
  {
    name: "Baby Fabric Shoes",
    price: "$4.00",
    originalPrice: "$5.00",
    rating: 5,
    img: "images/products/1.jpg",
  },
  {
    name: "Men's Hoodies T-Shirt",
    price: "$7.00",
    originalPrice: "$17.00",
    rating: 5,
    img: "images/products/2.jpg",
  },
  {
    name: "Girls T-Shirt",
    price: "$3.00",
    originalPrice: "$5.00",
    rating: 5,
    img: "images/products/clothes-1.jpg",
  },
  {
    name: "Woolen Hat For Men",
    price: "$12.00",
    originalPrice: "$15.00",
    rating: 5,
    img: "images/products/3.jpg",
  },
];

export const products = [
  {
    _id: "1",
    imageDefault: "images/products/jacket-3.jpg",
    imageHover: "images/products/jacket-2.jpg",
    badge: "",
    discount: "15%",
    category: "Jacket",
    title: "Mens Winter Leathers Jackets",
    rating: 5,
    price: 48.0,
    originalPrice: 75.0,
  },
  {
    _id: "2",
    imageDefault: "images/products/clothes-3.jpg",
    imageHover: "images/products/clothes-4.jpg",
    badge: "Sale",
    category: "Skirt",
    title: "Black Floral Wrap Midi Skirt",
    rating: 3,
    price: 45.0,
    originalPrice: 56.0,
  },
  {
    _id: "3",
    imageDefault: "images/products/shirt-1.jpg",
    imageHover: "images/products/shirt-2.jpg",
    badge: "New",
    badgeAngle: true,
    category: "Shirt",
    title: "Pure Garment Dyed Cotton Shirt",
    rating: 4,
    price: 45.0,
    originalPrice: 56.0,
  },
  {
    _id: "4",
    imageDefault: "images/products/party-wear-1.jpg",
    imageHover: "images/products/party-wear-2.jpg",
    badge: "Sale",
    badgeAngle: true,
    category: "party wear",
    title: "Womens Party Wear Shoes",
    rating: 2,
    price: 45.0,
    originalPrice: 56.0,
  },
  {
    _id: "5",
    imageDefault: "images/products/party-wear-1.jpg",
    imageHover: "images/products/party-wear-2.jpg",
    badge: "Sale",
    badgeAngle: true,
    category: "party wear",
    title: "Womens Party Wear Shoes",
    rating: 2,
    price: 45.0,
    originalPrice: 56.0,
  },
  {
    _id: "6",
    imageDefault: "images/products/clothes-3.jpg",
    imageHover: "images/products/clothes-4.jpg",
    badge: "Sale",
    category: "Skirt",
    title: "Black Floral Wrap Midi Skirt",
    rating: 3,
    price: 45.0,
    originalPrice: 56.0,
  },
  {
    _id: "7",
    imageDefault: "images/products/jacket-3.jpg",
    imageHover: "images/products/jacket-2.jpg",
    badge: "",
    discount: "15%",
    category: "Jacket",
    title: "Mens Winter Leathers Jackets",
    rating: 5,
    price: 48.0,
    originalPrice: 75.0,
  },
  {
    _id: "8",
    imageDefault: "images/products/shirt-1.jpg",
    imageHover: "images/products/shirt-2.jpg",
    badge: "New",
    badgeAngle: true,
    category: "Shirt",
    title: "Pure Garment Dyed Cotton Shirt",
    rating: 4,
    price: 45.0,
    originalPrice: 56.0,
  },
];

export const testimonials = [
  {
    name: "Alan Doe",
    image: "images/prof-4.jpg",
    title: "CEO & Founder Invasion",
    description:
      "I visited business  and tried product or service the customer used. The experience was great, it advantage enjoyed by the customer. I'd highly recommend them to anyone.",
  },
  {
    name: "Nina Parker",
    image: "images/prof-3.jpg",
    title: "senior Designer",
    description:
      "I recently purchased the product , and it has transformed how I manage my business. The user-friendly interface and powerful analytics tools have saved me hours of work each week. I highly recommend it for any small business owner",
  },
  {
    name: "Tommy Hill",
    image: "images/prof-1.jpg",
    title: "Technical Manager",
    description:
      "I was so impressed with the service  that I received from Eset. The staff was adjective, and they went above and beyond to help me with my issue. I would definitely recommend them to anyone",
  },
  // {
  //   name: "Tommy Hill",
  //   image: "images/prof-1.jpg",
  //   title: "Technical Manager",
  //   description:
  //     "I was so impressed with the service  that I received from Eset. The staff was adjective, and they went above and beyond to help me with my issue. I would definitely recommend them to anyone",
  // },
];

export const blogs = [
  {
    id: 1,
    image: "images/blog-1.jpg",
    category: "Fashion",
    title: "Clothes Retail KPIs 2021 Guide for Clothes Executives.",
    author: "Mr Admin",
    date: "Apr 06, 2022",
  },
  {
    id: 2,
    image: "images/blog-2.jpg",
    category: "Clothes",
    title: "Curbside fashion Trends: How to Win the Pickup Battle.",
    author: "Mr Robin",
    date: "Jan 18, 2022",
  },
  {
    id: 3,
    image: "images/blog-3.jpg",
    category: "Shoes",
    title: "EBT vendors: Claim Your Share of SNAP Online Revenue.",
    author: "Mr Selsa",
    date: "Feb 10, 2022",
  },
  {
    id: 4,
    image: "images/blog-4.jpg",
    category: "Electronics",
    title: "Curbside fashion Trends: How to Win the Pickup Battle.",
    author: "Mr Pawar",
    date: "Mar 15, 2022",
  },
];

export const footerCategories = [
  {
    title: "Fashion",
    links: [
      "T-shirt",
      "Shirts",
      "Shorts & Jeans",
      "Jacket",
      "Dress & Frock",
      "Innerwear",
      "Hosiery",
    ],
  },
  {
    title: "Footwear",
    links: [
      "Sport",
      "Formal",
      "Boots",
      "Casual",
      "Cowboy Shoes",
      "Safety Shoes",
      "Party Wear Shoes",
      "Branded",
      "Firstcopy",
      "Long Shoes",
    ],
  },
  {
    title: "Jewellery",
    links: [
      "Necklace",
      "Earrings",
      "Couple Rings",
      "Pendants",
      "Crystal",
      "Bangles",
      "Bracelets",
      "Nosepin",
      "Chain",
    ],
  },
  {
    title: "Cosmetics",
    links: [
      "Shampoo",
      "Bodywash",
      "Facewash",
      "Makeup Kit",
      "Liner",
      "Lipstick",
      "Perfume",
      "Body Soap",
      "Scrub",
      "Hair Gel",
      "Hair Colors",
      "Hair Dye",
      "Sunscreen",
      "Skin Lotion",
    ],
  },
];

export const navLinks = [
  {
    title: "Popular Categories",
    links: ["Fashion", "Electronic", "Cosmetic", "Health", "Watches"],
  },
  {
    title: "Products",
    links: [
      "Prices Drop",
      "New Products",
      "Best Sales",
      "Contact Us",
      "Sitemap",
    ],
  },
  {
    title: "Our Company",
    links: [
      "Delivery",
      "Legal Notice",
      "Terms & Conditions",
      "About Us",
      "Secure Payment",
    ],
  },
  {
    title: "Services",
    links: [
      "Prices Drop",
      "New Products",
      "Best Sales",
      "Contact Us",
      "Sitemap",
    ],
  },
];
